name: Deploy CDK Stack

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

on:
  push:
    branches:
      - main

jobs:
  lint-test-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: CDK Diff
        run: |
          set -e
          npx cdk diff
        continue-on-error: false

  deploy-dev:
    needs: lint-test-diff
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials (Dev)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::248896117205:role/evinovadevops-github-oidc-role-dev
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Dev
        run: npx cdk deploy --require-approval never

  approval-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://your-prod-url.example.com
    steps:
      - name: Manual approval for prod deploy
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy-prod:
    needs: approval-prod
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://your-prod-url.example.com
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials (Prod)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::248896117205:role/evinovadevops-github-oidc-role-prod
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Prod
        run: npx cdk deploy --require-approval never
